@startuml
object projects
projects : id
projects : name
projects : color

object tasks
tasks : id
tasks : user_id
tasks : name
tasks : date

projects "1" -right-  "    1..*"  tasks :"                   "
@enduml