@startuml

left to right direction
skinparam packageStyle rectangle
actor user
user -> (Start)

Rectangle System {
user --> (Lister les tâches des projets)
(Lister les tâches des projets) .> (Supprimer une tâche):extends
user --> (Ajouter une tâche)

(Lister les tâches des projets) .> (Trier les taches):extends
(Trier les taches) .>  (De A à Z):extends
(Trier les taches) .> (De Z à A):extends
(Trier les taches) .> (+Récentes --> +Anciennes):extends
(Trier les taches) .> (+Anciennes --> +Récentes):extends
}

@enduml