@startuml

left to right direction
skinparam packageStyle rectangle
actor user
user -> (Start)

Rectangle System {
user --> (Lister les tâches des projets)
user --> (Supprimer une tâche)
user --> (Ajouter une tâche)
user --> (Trier les taches)

(Trier les taches) <|-- (+Récentes --> +Anciennes)
(Trier les taches) <|- (+Anciennes --> +Récentes)
(Trier les taches) <|--  (De A à Z)
(Trier les taches) <|-- (De Z à A)
}

@enduml